### ISSUE TITLE
Guiones de 2020-2021. 

### ISSUE THREAD

**Issue by juanjimenez** [UCM-237/LCC#1]
Hay que usar los guiones de este curso para ir acompasados con el resto de los grupos. Están disponibles en las carpeta LCC_mios del drive.

**Comment by noether** [comment]
Hecho, ya he subido la practica1_2021

**Comment by juanjimenez** [comment]
Gracias,
Mañana te pregunto algunas cosas para trabajar en GitHub con cabeza :b
He añadido en la entrada des campus del manual un enlace al repositorio del
manual
